### ISSUE TITLE
Stable http4s for CE3

### ISSUE THREAD

**Issue by keynmol** [ovotech/natchez-extras#66]
Howdy folks! We're evaluating using this library, but one thing that stood out to me was usage of `1.0.0-M*` in http4s integration.

Is there a particular feature 1.0 brings that is required for the integration?

Problem with `1.0.0-M*` lineage in http4s is that milestones are not binary compatible (and the date for final release of 1.x is not really set), unlike the stable `0.23.*` lineage which is using CE3

**Comment by tomverran** [comment]
Hi sorry about the slow reply, we switched to 1.0.0-M* initially because at that time 0.x was only CE2 (at least, I thought it was :sweat_smile: ) - I don't think we realised the caveats about binary compatibility but it does make sense to switch back to 0.23 now that CE3 is available, I'll try doing it today

**Comment by keynmol** [comment]
Thanks! And yeah, no worries - getting all the versions right in great schism of CE2-3 is a herculean task :)
